### ISSUE TITLE
We need to assess the need for other supporting materials

### ISSUE THREAD

**Issue by davidbhayes** [CodeForFoco/reclaim-fort-collins#3]
The City's checklist (http://www.fcgov.com/environmentalservices/pdf/ifcc-application-checklist.pdf) suggests:

> Supporting Documentation including:
>  * Project work plan (required -- separate issue)
>  * Project budget (required -- separate issue)
>  * Proof of insurance (if applicable)
>  * Letters of support from key stakeholders (optional but recommended)
>  * One-page summary of past performance (optional but recommended)

**Comment by JordanMajd** [comment]
Done
