### ISSUE TITLE
(Last step) We need to submit the application to the city

### ISSUE THREAD

**Issue by davidbhayes** [CodeForFoco/reclaim-fort-collins#6]
From the checklist: 

> ## APPLICATION SUBMISSION 
> Completed applications, including all required documentation, should be submitted to innovate@fcgov.com with the subject line “IFCC Application.” To submit the concept video applicants may upload the video file to Youtube or Vimeo and must include the link in the application email submission. Do not attach a video file with your application, it may cause your email to be rejected. All applications will receive an electronic confirmation of receipt from City of Fort Collins staff.

**Comment by JordanMajd** [comment]
Done
